services:
  echoguide-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: echoguide-frontend
    ports:
      - "5175:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
